INSERT INTO users (email, residenceType)
    VALUES ("example@example.com", "apartment")
INSERT INTO users (email, residenceType)
    VALUES ("myemail@test.com", "house")
INSERT INTO users (email, residenceType)
    VALUES ("test@test.com", "teepee")